version: "3.9"

services:

  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ../../data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:alpine

  celery:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../:/opt/OnlineAuctions/
    entrypoint: docker/local/celery_entrypoint.sh
    depends_on:
      - rabbitmq

  celery-beat:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../:/opt/OnlineAuctions/
    entrypoint: docker/local/celery_beat_entrypoint.sh
    depends_on:
      - rabbitmq

  web:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../:/opt/OnlineAuctions/
    entrypoint: docker/local/web_entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
      - celery-beat
