version: "3.9"

services:

  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ../../data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
